os: linux
language: python
dist: xenial
jobs:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install xarray
  - pip install matplotlib
# Travis CI currently not working with netCDF4 1.5.3
  - pip install 'cftime==1.1.1'
  - pip install 'netCDF4<1.5.3'
# Install pysatCDF and dump output
  - pip install pysatCDF >/dev/null
  # Prepare pysat install from git
  - cd ..
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - cd ./pysat
  # install pysat
  - git checkout download_flags
  - python setup.py install >/dev/null
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd ../pysatModels

install:
  - python setup.py install

script:
  - pytest -vs --cov=pysatModels/

after_success:
  - coveralls
