language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.7

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib
  - pip install netCDF4
  - pip install beautifulsoup4
  - pip install lxml
  - pip install pysatCDF >/dev/null
  
install:
  - python setup.py install

script:
  - pytest -vs --cov=pysatModelUtils/

after_success:
  - coveralls
