os: linux
language: python
dist: xenial
jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb
addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install xarray
  - pip install matplotlib
  # Install pysatCDF and dump output
  - pip install pysatCDF >/dev/null
  # Prepare pysat install from git
  - cd ..
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - cd ./pysat
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - git checkout develop-3
  - python setup.py install >/dev/null
  - cd ../pysatModels

install:
  - python setup.py install

script:
  - pytest -vs --cov=pysatModels/

after_success:
  - coveralls
