os: linux
language: python
dist: xenial
jobs:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
addons:
  apt:
    packages:
    - gfortran

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests beautifulsoup4 lxml netCDF4 nose pytest-cov pytest-ordering coveralls future
  - conda activate test-environment
  - pip install pysatCDF >/dev/null
  # Prepare pysat install from git
  - cd ..
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - cd ./pysat
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - git checkout develop-3
  - python setup.py install >/dev/null
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd ../pysatModels

install:
  - python setup.py install

script:
  - pytest -vs --cov=pysatModels/  --flake8

after_success:
  - coveralls
