language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib
  - pip install netCDF4
  - pip install 'pandas<0.25'
  - pip install xarray
  - pip install pysatCDF >/dev/null
  # Prepare modified pysat install
  - pip install numpy
  - cd ..
  - echo 'cloning pysat'
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - echo 'installing pysat'
  - cd ./pysat
  - git checkout develop
  # set up data directory
  - mkdir /home/travis/build/pysat/pysatData
  # install pysat
  - cd /home/travis/build/pysat/pysat
  - python setup.py install >/dev/null
  - cd /home/travis/build/pysat/pysatModelUtils


install:
  - python setup.py install

script:
  - pytest -vs --cov=pysatModelUtils/

after_success:
  - coveralls
